create table health_checks (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  is_healthy boolean not null,
  response_time integer not null,
  status_code integer not null,
  error_message text,
  created_at timestamptz default now()
);

-- יצירת אינדקס על שדה הזמן לשיפור ביצועים
create index health_checks_timestamp_idx on health_checks(timestamp); 