create table kaggle_updates (
  id bigint generated by default as identity primary key,
  timestamp timestamptz not null,
  is_updated boolean not null,
  last_update timestamptz,
  error_message text,
  created_at timestamptz default now()
);

-- יצירת אינדקס על שדה הזמן
create index kaggle_updates_timestamp_idx on kaggle_updates(timestamp);