# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Data to Kaggle


on: 
  schedule:
    - cron: '00 20 * * *'
  workflow_dispatch:

  
jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    steps:
    - name: Clean Old
      run: |
        sudo rm -rf "${{ github.workspace }}"
        mkdir "${{ github.workspace }}"
      
    - name: Checkout
      uses: actions/checkout@v3
    - name: Free disk space
      run: |
        df --human-readable
        sudo apt clean
        docker 2>/dev/null 1>&2 rmi $(docker image ls --all --quiet) || true
        rm --recursive --force "$AGENT_TOOLSDIRECTORY"
        df --human-readable
    - name: Build with Docker
      run: docker build -t erlichsefi/israeli-supermarket-publisher:prod --target prod .
    - name: Remove all build
      run: (docker stop publisher-runner 2>/dev/null || true) && (docker rm publisher-runner 2>/dev/null || true)
    - name: Daily Dump
      run: |
           mkdir -p app_data &&
           docker run --rm \
            -v ./app_data:/usr/src/app/app_data \
            -e KAGGLE_KEY=$KAGGLE_KEY \
            -e KAGGLE_USERNAME=$KAGGLE_USERNAME \
            --name publisher-runner erlichsefi/israeli-supermarket-publisher:prod &&
           docker builder prune -f