name: Deploy to Runner Machine

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # Important: Use a self-hosted runner

    steps:
      - uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
          docker build -t erlichsefi/israeli-supermarket-publisher:prod --target serving .

      - name: Start Docker daemon (if not already running)
        run: sudo systemctl start docker || true # Start if not already running

      - name: Run Docker Compose
        if: ${{ matrix.compose }}
        uses: docker/compose-action@v3
        with:
          compose-file: docker-compose.yml # Path to your docker-compose.yml
          up: true
          down: false # Don't automatically tear down on workflow completion