# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrape Itreation 

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    env:
      OPERATION: ${{ inputs.operation }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build with Docker
      run: docker compose build

    - name: Print workspace
      run: echo ${{ env.GITHUB_WORKSPACE }}

    - name: Make sure folders exists
      run: |-
          mkdir -p  ${{ env.GITHUB_WORKSPACE }}/mongo_data &&
          mkdir -p  ${{ env.GITHUB_WORKSPACE }}/app_data

    - name: Make sure Mongo Up
      run: docker compose up -d mongodb

    - name: Process Request
      run:  OPREATION="${{ env.OPERATION }}" KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} APP_DATA_PATH=${{ env.GITHUB_WORKSPACE }}/app_data MONGO_DATA_PATH=${{ env.GITHUB_WORKSPACE }}/mongo_data docker compose up publisher 