# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Template

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    env:
      OPERATION: ${{ inputs.operation }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Adding env variables
      run: |
        echo "APP_DATA_PATH=${{ runner.workspace }}/app_data" >> $GITHUB_ENV
        echo "MONGO_DATA_PATH=${{ runner.workspace }}/mongo_data" >> $GITHUB_ENV
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV
        echo "OPREATION=${{ inputs.operation }}" >> $GITHUB_ENV

    - name: Build with Docker
      run: docker compose build

    - name: Make sure Mongo UP
      run: docker compose up -d mongodb 

    - name: Process Request
      run: docker compose up publisher

    # act -W '.github/workflows/template.yml' -P self-hosted=catthehacker/ubuntu:act-latest