# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrape Itreation 

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    env:
      OPERATION: ${{ inputs.operation }}

    steps:
    # TBD: removing old code will remove the data folder too
    # - name: Clean Old 
    #   run: |
    #     sudo rm -rf "${{ github.workspace }}"
    #     mkdir "${{ github.workspace }}"
      
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Free disk space
    #   run: |
    #     df --human-readable
    #     docker 2>/dev/null 1>&2 rmi $(docker image ls --all --quiet) || true
    #     rm --recursive --force "$AGENT_TOOLSDIRECTORY"
    #     df --human-readable
    - name: Build with Docker
      run: docker compose build

    - name: Make sure App Data folder exists
      run: mkdir -p  ${{ runner.workspace }}/app_data

    - name: Make sure Mongo Up
      run: docker compose up -d mongodb

    - name: Process Request
      run:  OPREATION="${{ env.OPERATION }}" \
            KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} \ 
            KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} \ 
            APP_DATA_PATH=${{ runner.workspace }}/app_data \ 
            MONGO_DATA_PATH=${{ runner.workspace }}/mongo_data \ 
            docker-compose up publisher 