# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Scrape Itreation 

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    env:
      OPERATION: ${{ inputs.operation }}

    steps:
    # TBD: removing old code will remove the data folder too
    # - name: Clean Old 
    #   run: |
    #     sudo rm -rf "${{ github.workspace }}"
    #     mkdir "${{ github.workspace }}"
      
    - name: Checkout
      uses: actions/checkout@v3
    - name: Free disk space
      run: |
        df --human-readable
        docker 2>/dev/null 1>&2 rmi $(docker image ls --all --quiet) || true
        rm --recursive --force "$AGENT_TOOLSDIRECTORY"
        df --human-readable
    - name: Build with Docker
      run: docker compose build
    - name: Remove all build
      run: (docker stop publisher-runner 2>/dev/null || true) && (docker rm publisher-runner 2>/dev/null || true)
    - name: Process Request
      run:  mkdir -p  ${{ runner.workspace }}/app_data && \
            docker-compose up -d mongodb && \
            while ! docker-compose exec mongodb mongosh --eval "db.runCommand('ping').ok" --quiet; do
                echo "waiting for MongoDB..."
                sleep 2
            done && \
            docker-compose up \
            -v ${{ runner.workspace }}/app_data:/usr/src/app/app_data \
            -e KAGGLE_KEY=${{ secrets.KAGGLE_KEY }} \
            -e KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }} \
            -e OPREATION="${{ env.OPERATION }}" \
            publisher &&
           docker builder prune -f