# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Template

on:
  workflow_call:
    inputs:
      operation:
        required: true
        type: string
      branch:
        type: string
        default: 'main'
      environment:
        type: string
        default: 'production'
      kaggle_dataset_remote_name:
        type: string
        default: 'test-super-dataset-2'
jobs:
  build:

    runs-on: 
      - self-hosted
      - ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]


    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}


    - name: Set enabled scrapers
      run: |
        echo "ENABLED_SCRAPERS=${{ inputs.enabled_scrapers }}" >> $GITHUB_ENV

    - name: Set enabled file types
      run: |
        echo "ENABLED_FILE_TYPES=${{ inputs.enabled_file_types }}" >> $GITHUB_ENV
        
    - name: Adding env variables
      run: |
        echo "APP_DATA_PATH=${{ env.GITHUB_WORKSPACE }}/app_data" >> $GITHUB_ENV
        echo "MONGO_DATA_PATH=${{ env.GITHUB_WORKSPACE }}/mongo_data" >> $GITHUB_ENV
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> $GITHUB_ENV
        echo "MONGO_PORT=${{ secrets.MONGO_PORT }}" >> $GITHUB_ENV
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
        echo "KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}" >> $GITHUB_ENV
        echo "KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}" >> $GITHUB_ENV
        echo "OPERATION=${{ inputs.operation }}" >> $GITHUB_ENV
        echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> $GITHUB_ENV
        echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV
        echo "KAGGLE_DATASET_REMOTE_NAME=${{ inputs.kaggle_dataset_remote_name }}" >> $GITHUB_ENV
        echo "ENABLED_SCRAPERS=${{ secrets.ENABLED_SCRAPERS }}" >> $GITHUB_ENV
        echo "ENABLED_FILE_TYPES=${{ secrets.ENABLED_FILE_TYPES }}" >> $GITHUB_ENV
        
    - name: Build with Docker
      run: docker compose build

    - name: Make sure Mongo UP
      run: docker compose up -d mongodb 

    - name: Process Request
      run: docker compose up data_processor

    # act -W '.github/workflows/template.yml' -P self-hosted=catthehacker/ubuntu:act-latest